services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - TZ=UTC
      - PGTZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.ops/docker/db/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
      - shared
    ports:
      - '127.0.0.1:5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_CONFIG_SERVER_MODE=False
    networks:
      - backend
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  api:
    command: sh -c "npx prisma generate && npx nx serve backend --watch --host=0.0.0.0"
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    environment:
      - PORT=3000
      - NODE_ENV=development
      - NX_DAEMON=false
      - NX_REJECT_UNKNOWN_LOCAL_CACHE=0
      - ALLOWED_ORIGIN=http://localhost:4200
      - KEYCLOAK_REALM=demo_shop
      - KEYCLOAK_CLIENT_API=demo_shop_api
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_REALM_PUBLIC_KEY
      - SENTRY_AUTH_TOKEN
      - SENTRY_ORG
      - SENTRY_TRUSTED_DOMAIN=http://localhost
      - SENTRY_DEMO_SHOP_API_DSN
      - SENTRY_DEMO_SHOP_API_PROJECT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - backend
      - frontend
      - shared

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev --import-realm
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://host.docker.internal/keycloak
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./.ops/docker/keycloak/imports:/opt/keycloak/data/import
    ports:
      - '8080:8080'
    networks:
      - frontend
      - backend
      - shared

  frontend:
    command: npx nx serve frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      target: dev
    environment:
      - API_URL=http://api:3000
      - NODE_ENV=development
      - KEYCLOAK_URL=http://localhost:8080
      - SENTRY_DEMO_SHOP_UI_DSN
      - SENTRY_TRUSTED_DOMAIN=http://localhost
    ports:
      - '4200:4200'
    volumes:
      - .:/app:cached
      - /app/node_modules
    networks:
      - frontend
      - shared
    depends_on:
      - api

volumes:
  postgres_data:
  pgadmin_data:

networks:
  frontend:
  backend:
  shared:
    external: true
