services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - '127.0.0.1:5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_CONFIG_SERVER_MODE=False
    networks:
      - backend
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    command: sh -c "npx prisma generate && npx nx serve backend --watch --host=0.0.0.0"
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    env_file:
      - .env
      - ./secrets/sentry-config.txt
    environment:
      - PORT=3000
      - NODE_ENV=development
      - NX_DAEMON=false
      - NX_REJECT_UNKNOWN_LOCAL_CACHE=0
      - DATABASE_URL
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_API
      - KEYCLOAK_REALM_PUBLIC_KEY
      - KEYCLOAK_URL
      - POSTGRES_HOST=db
      - SENTRY_AUTH_TOKEN
      - SENTRY_ORG
      - SENTRY_TRUSTED_DOMAIN
      - SENTRY_DEMO_SHOP_API_DSN
      - SENTRY_DEMO_SHOP_API_PROJECT
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - backend
      - frontend

  prisma:
    image: docker.io/node:lts-alpine
    working_dir: /usr/src/app
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c "
      npx prisma migrate dev &&
      npx prisma db seed
      "
    depends_on:
      - db
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - frontend

  frontend:
    command: npx nx serve frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      target: dev
    env_file:
      - .env
      - ./secrets/sentry-config.txt
    environment:
      - DEMO_SHOP_API_URL=http://backend:3000
      - SENTRY_DEMO_SHOP_UI_DSN
      - SENTRY_TRUSTED_DOMAIN
      - API_URL=http://backend:3000
    ports:
      - '4200:4200'
    volumes:
      - .:/app:cached
      - /app/node_modules
    networks:
      - frontend
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  frontend:
  backend:
