services:
  backend:
    environment:
      - NODE_ENV=development
    build:
      target: dev
    command: npx nx serve backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build:
      target: dev
    command: npx nx serve frontend
    ports:
      - '4200:4200'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
