apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8080
      #    - port: 8443
      targetPort: 8080
      #      targetPort: 8443
      nodePort: 30081
