apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KC_DB_URL: '${KC_DB_URL}'
  KEYCLOAK_URL: '${KEYCLOAK_URL}'
  KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
  KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN}'
  KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
  KC_DB_USERNAME: '${POSTGRES_USER}'
  KC_DB_PASSWORD: '${POSTGRES_PASSWORD}'
