apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-job
spec:
  template:
    spec:
      containers:
        - name: prisma
          image: prisma:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: 'postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)?schema=public'
          envFrom:
            - configMapRef:
                name: prisma-config
            - secretRef:
                name: prisma-secrets
          command: ['npx', 'prisma', 'migrate', 'deploy']
      restartPolicy: Never
