/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpValidationProblemDetails } from './http-validation-problem-details';
import { ProblemDetails } from './problem-details';

/**
 * @type AddCartItem401Response
 * @export
 */
export type AddCartItem401Response = HttpValidationProblemDetails | ProblemDetails;
