/**
 * Demo shop
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AddressDTO {
  readonly street: string;
  readonly apartment: string;
  readonly city: string;
  readonly region: string;
  readonly zip: string;
  readonly country: string;
}
