/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AddressResponse {
  street: string;
  apartment: string;
  city: string;
  region?: string | null;
  zip: string;
  country: string;
}
