/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CartItemResponse {
  id: number;
  productId: number;
  productName: string;
  productThumbnail: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}
