/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './order-status';
import { OrderItemResponse } from './order-item-response';

export interface OrderResponse {
  id: number;
  userId: number;
  items: Array<OrderItemResponse>;
  amount: number;
  status: OrderStatus;
  created: string;
}
