/**
 * Demo shop
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OrderItemDTO {
  readonly productId: number;
  readonly productName: string;
  readonly productThumbnail: string;
  readonly quantity: number;
  readonly unitPrice: number;
  readonly totalPrice: number;
}
