/**
 * Demo shop
 * The demo shop API description
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './order-status';
import { OrderItemDTO } from './order-item-dto';

export interface OrderDTO {
  readonly id: string;
  readonly userId: string;
  readonly items: Array<OrderItemDTO>;
  readonly amount: number;
  status: OrderStatus;
  readonly created: string;
}
