/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageResponse } from './image-response';

export interface ProductResponse {
  id: number;
  name: string;
  description: string;
  categories: Array<string>;
  images: Array<ImageResponse>;
  price: number;
  thumbnail: ImageResponse;
}
