/**
 * Demo shop
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageDTO } from './image-dto';

export interface ProductDTO {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly categories: Array<string>;
  readonly images: Array<ImageDTO>;
  readonly price: number;
}
