/**
 * Demo shop
 * The demo shop API description
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemDTO } from './cart-item-dto';

export interface ShoppingSessionDTO {
  readonly id: string;
  readonly userId: string;
  readonly items: Array<CartItemDTO>;
}
