/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemResponse } from './cart-item-response';

export interface ShoppingSessionResponse {
  id: number;
  userId: number;
  items: Array<CartItemResponse>;
}
