/**
 * Demo shop
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemDTO } from './cart-item-dto';

export interface ShoppingSessionDTO {
  readonly id: number;
  readonly userId: number;
  readonly items: Array<CartItemDTO>;
}
