/**
 * Demo Shop API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateCartItemQuantityRequest } from './update-cart-item-quantity-request';

export interface UpdateCartItemQuantityRequestWrapper {
  id: number;
  updateCartItemQuantityRequest: UpdateCartItemQuantityRequest;
}
