export const mockOrders = [
  {
    id: 1,
    amount: 1710,
    created: '2024-10-17T16:09:05.396Z',
    items: [
      {
        productId: 1,
        productName: 'Unbranded Marble Computer',
        productThumbnail: 'https://picsum.photos/seed/oVSyWaHw/2064/328?grayscale',
        quantity: 5,
        unitPrice: 39,
        totalPrice: 195,
      },
      {
        productId: 2,
        productName: 'Sleek Aluminum Pants',
        productThumbnail: 'https://picsum.photos/seed/GLkLT/1905/2429',
        quantity: 4,
        unitPrice: 139,
        totalPrice: 556,
      },
      {
        productId: 3,
        productName: 'Oriental Aluminum Hat',
        productThumbnail: 'https://picsum.photos/seed/LizIRo/244/1061?grayscale&blur=10',
        quantity: 1,
        unitPrice: 139,
        totalPrice: 139,
      },
      {
        productId: 4,
        productName: 'Ergonomic Concrete Keyboard',
        productThumbnail: 'https://picsum.photos/seed/ixOFihYbEo/3190/1023?blur=1',
        quantity: 3,
        unitPrice: 79,
        totalPrice: 237,
      },
      {
        productId: 5,
        productName: 'Sleek Concrete Salad',
        productThumbnail: 'https://picsum.photos/seed/sChOI9Av/3580/1416?blur=7',
        quantity: 2,
        unitPrice: 129,
        totalPrice: 258,
      },
      {
        productId: 6,
        productName: 'Fresh Granite Mouse',
        productThumbnail: 'https://picsum.photos/seed/O9UhsjNDhO/1703/802?grayscale&blur=9',
        quantity: 2,
        unitPrice: 89,
        totalPrice: 178,
      },
      {
        productId: 7,
        productName: 'Frozen Rubber Soap',
        productThumbnail: 'https://picsum.photos/seed/FBcppSl/3627/3834?blur=8',
        quantity: 3,
        unitPrice: 49,
        totalPrice: 147,
      },
    ],
    status: 'Created',
    userId: 0,
  },
  {
    id: 2,
    amount: 533,
    created: '2024-08-26T12:45:49.308Z',
    items: [
      {
        productId: 1,
        productName: 'Luxurious Gold Keyboard',
        productThumbnail: 'https://picsum.photos/seed/5a85viLn/3777/3086?blur=6',
        quantity: 3,
        unitPrice: 19,
        totalPrice: 57,
      },
      {
        productId: 2,
        productName: 'Intelligent Rubber Table',
        productThumbnail: 'https://picsum.photos/seed/1eNw96Ak/2264/411?blur=8',
        quantity: 4,
        unitPrice: 119,
        totalPrice: 476,
      },
    ],
    status: 'Completed',
    userId: 0,
  },
  {
    id: 3,
    amount: 129,
    created: '2024-06-19T20:16:18.948Z',
    items: [
      {
        productId: 1,
        productName: 'Practical Metal Ball',
        productThumbnail: 'https://picsum.photos/seed/BRRcqWl9V/397/567?grayscale&blur=1',
        quantity: 1,
        unitPrice: 129,
        totalPrice: 129,
      },
    ],
    status: 'Created',
    userId: 0,
  },
  {
    id: 4,
    amount: 1634,
    created: '2024-06-01T11:51:09.570Z',
    items: [
      {
        productId: 1,
        productName: 'Recycled Granite Computer',
        productThumbnail: 'https://picsum.photos/seed/rymvPe/1133/1778?grayscale&blur=7',
        quantity: 1,
        unitPrice: 59,
        totalPrice: 59,
      },
      {
        productId: 2,
        productName: 'Fresh Marble Fish',
        productThumbnail: 'https://picsum.photos/seed/cMJZ2/187/2387?grayscale&blur=8',
        quantity: 1,
        unitPrice: 29,
        totalPrice: 29,
      },
      {
        productId: 3,
        productName: 'Soft Cotton Fish',
        productThumbnail: 'https://picsum.photos/seed/mpBpkG/2215/3975?grayscale&blur=4',
        quantity: 2,
        unitPrice: 89,
        totalPrice: 178,
      },
      {
        productId: 4,
        productName: 'Tasty Concrete Table',
        productThumbnail: 'https://picsum.photos/seed/GqUuE7JRGb/2502/2943?grayscale&blur=3',
        quantity: 2,
        unitPrice: 79,
        totalPrice: 158,
      },
      {
        productId: 5,
        productName: 'Rustic Metal Computer',
        productThumbnail: 'https://picsum.photos/seed/E59PLzNm/1631/2560?grayscale&blur=7',
        quantity: 4,
        unitPrice: 19,
        totalPrice: 76,
      },
      {
        productId: 6,
        productName: 'Frozen Marble Ball',
        productThumbnail: 'https://picsum.photos/seed/an3XWhGang/1356/1281?grayscale&blur=6',
        quantity: 3,
        unitPrice: 179,
        totalPrice: 537,
      },
      {
        productId: 7,
        productName: 'Elegant Bamboo Cheese',
        productThumbnail: 'https://picsum.photos/seed/IbgziXXsB/2975/829?blur=9',
        quantity: 3,
        unitPrice: 199,
        totalPrice: 597,
      },
    ],
    status: 'Completed',
    userId: 0,
  },
  {
    id: 5,
    amount: 1906,
    created: '2024-03-28T00:12:00.886Z',
    items: [
      {
        productId: 1,
        productName: 'Recycled Plastic Shoes',
        productThumbnail: 'https://picsum.photos/seed/6pJbPA/343/320?grayscale&blur=1',
        quantity: 4,
        unitPrice: 119,
        totalPrice: 476,
      },
      {
        productId: 2,
        productName: 'Elegant Ceramic Car',
        productThumbnail: 'https://picsum.photos/seed/ssVH0/2689/1046',
        quantity: 4,
        unitPrice: 99,
        totalPrice: 396,
      },
      {
        productId: 3,
        productName: 'Small Silk Ball',
        productThumbnail: 'https://picsum.photos/seed/vtV2XnPft/730/2158?blur=9',
        quantity: 5,
        unitPrice: 39,
        totalPrice: 195,
      },
      {
        productId: 4,
        productName: 'Practical Granite Car',
        productThumbnail: 'https://picsum.photos/seed/1KSSmVlt4/2384/2461?blur=6',
        quantity: 3,
        unitPrice: 99,
        totalPrice: 297,
      },
      {
        productId: 5,
        productName: 'Sleek Cotton Shirt',
        productThumbnail: 'https://picsum.photos/seed/Jjq3b/1766/1807?blur=4',
        quantity: 3,
        unitPrice: 9,
        totalPrice: 27,
      },
      {
        productId: 6,
        productName: 'Modern Concrete Table',
        productThumbnail: 'https://picsum.photos/seed/iTTOs2Ta/3751/3455?blur=7',
        quantity: 2,
        unitPrice: 79,
        totalPrice: 158,
      },
      {
        productId: 7,
        productName: 'Handmade Silk Table',
        productThumbnail: 'https://picsum.photos/seed/FdtEWDMx/2482/2469',
        quantity: 3,
        unitPrice: 119,
        totalPrice: 357,
      },
    ],
    status: 'Created',
    userId: 0,
  },
  {
    id: 6,
    amount: 329,
    created: '2024-04-07T04:32:57.173Z',
    items: [
      {
        productId: 1,
        productName: 'Sleek Bamboo Tuna',
        productThumbnail: 'https://picsum.photos/seed/QwD7ZsgU/542/2688?grayscale&blur=8',
        quantity: 2,
        unitPrice: 39,
        totalPrice: 78,
      },
      {
        productId: 2,
        productName: 'Oriental Gold Bacon',
        productThumbnail: 'https://picsum.photos/seed/iTmpLAB/404/795?grayscale&blur=10',
        quantity: 5,
        unitPrice: 19,
        totalPrice: 95,
      },
      {
        productId: 3,
        productName: 'Fantastic Bamboo Car',
        productThumbnail: 'https://picsum.photos/seed/Jq0pbj9/3427/920?grayscale&blur=4',
        quantity: 4,
        unitPrice: 39,
        totalPrice: 156,
      },
    ],
    status: 'Completed',
    userId: 0,
  },
  {
    id: 7,
    amount: 2298,
    created: '2025-03-08T09:55:31.096Z',
    items: [
      {
        productId: 1,
        productName: 'Sleek Bronze Pizza',
        productThumbnail: 'https://picsum.photos/seed/s4tUYEh/2781/2758?grayscale&blur=4',
        quantity: 5,
        unitPrice: 39,
        totalPrice: 195,
      },
      {
        productId: 2,
        productName: 'Small Metal Pizza',
        productThumbnail: 'https://picsum.photos/seed/8d8j0dr/1488/1136?blur=1',
        quantity: 5,
        unitPrice: 99,
        totalPrice: 495,
      },
      {
        productId: 3,
        productName: 'Oriental Granite Chips',
        productThumbnail: 'https://picsum.photos/seed/f7Q5453Asg/657/1446?grayscale&blur=6',
        quantity: 1,
        unitPrice: 49,
        totalPrice: 49,
      },
      {
        productId: 4,
        productName: 'Unbranded Marble Hat',
        productThumbnail: 'https://picsum.photos/seed/p4dlyEHpZ/2004/990?grayscale&blur=4',
        quantity: 3,
        unitPrice: 109,
        totalPrice: 327,
      },
      {
        productId: 5,
        productName: 'Handmade Marble Towels',
        productThumbnail: 'https://picsum.photos/seed/t94h0U/1940/3670?grayscale',
        quantity: 2,
        unitPrice: 109,
        totalPrice: 218,
      },
      {
        productId: 6,
        productName: 'Soft Metal Towels',
        productThumbnail: 'https://picsum.photos/seed/2XnipEr/1393/260?blur=5',
        quantity: 5,
        unitPrice: 19,
        totalPrice: 95,
      },
      {
        productId: 7,
        productName: 'Licensed Bamboo Table',
        productThumbnail: 'https://picsum.photos/seed/Fvon4q/1896/2367?blur=9',
        quantity: 3,
        unitPrice: 79,
        totalPrice: 237,
      },
      {
        productId: 8,
        productName: 'Refined Marble Shirt',
        productThumbnail: 'https://picsum.photos/seed/OPGN8pwq/3999/838?grayscale&blur=4',
        quantity: 5,
        unitPrice: 59,
        totalPrice: 295,
      },
      {
        productId: 9,
        productName: 'Tasty Silk Shirt',
        productThumbnail: 'https://picsum.photos/seed/O4PI1mk/3689/784?blur=9',
        quantity: 3,
        unitPrice: 129,
        totalPrice: 387,
      },
    ],
    status: 'Created',
    userId: 0,
  },
  {
    id: 8,
    amount: 997,
    created: '2024-09-29T09:50:00.551Z',
    items: [
      {
        productId: 1,
        productName: 'Modern Aluminum Chair',
        productThumbnail: 'https://picsum.photos/seed/ywuWftjhV/1783/3725?blur=1',
        quantity: 1,
        unitPrice: 9,
        totalPrice: 9,
      },
      {
        productId: 2,
        productName: 'Oriental Steel Soap',
        productThumbnail: 'https://picsum.photos/seed/VGYq7gM9M/3743/1688?grayscale&blur=9',
        quantity: 2,
        unitPrice: 149,
        totalPrice: 298,
      },
      {
        productId: 3,
        productName: 'Recycled Marble Pants',
        productThumbnail: 'https://picsum.photos/seed/LF5Sowwq3/763/2639?blur=4',
        quantity: 4,
        unitPrice: 139,
        totalPrice: 556,
      },
      {
        productId: 4,
        productName: 'Fresh Rubber Towels',
        productThumbnail: 'https://picsum.photos/seed/ZgEFuO/1227/1716?grayscale&blur=5',
        quantity: 5,
        unitPrice: 19,
        totalPrice: 95,
      },
      {
        productId: 5,
        productName: 'Fresh Gold Salad',
        productThumbnail: 'https://picsum.photos/seed/0bYTY/1421/3718?grayscale&blur=1',
        quantity: 1,
        unitPrice: 39,
        totalPrice: 39,
      },
    ],
    status: 'Completed',
    userId: 0,
  },
  {
    id: 9,
    amount: 1673,
    created: '2024-10-18T10:45:05.756Z',
    items: [
      {
        productId: 1,
        productName: 'Fantastic Rubber Hat',
        productThumbnail: 'https://picsum.photos/seed/JgO5M/2199/374?grayscale&blur=6',
        quantity: 4,
        unitPrice: 199,
        totalPrice: 796,
      },
      {
        productId: 2,
        productName: 'Generic Bronze Pizza',
        productThumbnail: 'https://picsum.photos/seed/FKwbfnl1/1089/895',
        quantity: 5,
        unitPrice: 39,
        totalPrice: 195,
      },
      {
        productId: 3,
        productName: 'Fresh Concrete Gloves',
        productThumbnail: 'https://picsum.photos/seed/44nOgAsWmh/3147/1095?grayscale&blur=8',
        quantity: 3,
        unitPrice: 199,
        totalPrice: 597,
      },
      {
        productId: 4,
        productName: 'Fantastic Bronze Salad',
        productThumbnail: 'https://picsum.photos/seed/18vkwX4Z/3068/2408?blur=1',
        quantity: 4,
        unitPrice: 9,
        totalPrice: 36,
      },
      {
        productId: 5,
        productName: 'Elegant Steel Shoes',
        productThumbnail: 'https://picsum.photos/seed/OoXYyAm/1958/3776?grayscale&blur=9',
        quantity: 1,
        unitPrice: 49,
        totalPrice: 49,
      },
    ],
    status: 'Created',
    userId: 0,
  },
  {
    id: 10,
    amount: 1112,
    created: '2025-02-22T02:00:14.780Z',
    items: [
      {
        productId: 1,
        productName: 'Handmade Metal Table',
        productThumbnail: 'https://picsum.photos/seed/mW17q0cPaf/3972/2503?blur=4',
        quantity: 5,
        unitPrice: 109,
        totalPrice: 545,
      },
      {
        productId: 2,
        productName: 'Sleek Plastic Fish',
        productThumbnail: 'https://picsum.photos/seed/N3mkd/2933/2252?grayscale&blur=3',
        quantity: 1,
        unitPrice: 199,
        totalPrice: 199,
      },
      {
        productId: 3,
        productName: 'Generic Granite Tuna',
        productThumbnail: 'https://picsum.photos/seed/OKDgcJTe2G/3013/1024?blur=5',
        quantity: 1,
        unitPrice: 189,
        totalPrice: 189,
      },
      {
        productId: 4,
        productName: 'Rustic Gold Towels',
        productThumbnail: 'https://picsum.photos/seed/YMLtm/1570/394?blur=1',
        quantity: 1,
        unitPrice: 179,
        totalPrice: 179,
      },
    ],
    status: 'Completed',
    userId: 0,
  },
];
