POST http://localhost:8081/realms/demo_shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = john@doe.com &
password = skewed-oversold-vividness &
grant_type = password &
client_id = demo_shop_ui

###

POST http://localhost:8081/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = admin &
password = CN6%26%25hdvdFCe &
grant_type = password &
client_id = admin-cli

###

GET http://localhost:8081/admin/realms
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlSFBjTjhrUzQ4aElwbmUxc2JSWnBJblp2dlhrRGFfSHFPdnBxMWVnOGRrIn0.eyJleHAiOjE3Mjc5NDQxMzEsImlhdCI6MTcyNzk0NDA3MSwianRpIjoiODhhOTY5NmUtOGNmNS00NmFmLWJiMDAtNjc3NTJiMjU2MzNkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiIwM2U1ZDhiOS0zOTZmLTQ4MzgtOGMwMS1iMWQ0Nzc1M2Y3MWQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiYWI4NDZlNDItMDQyOS00NjJjLWE2Y2EtOTg2ZDdhMTk5ZTNjIiwiYWNyIjoiMSIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6ImFiODQ2ZTQyLTA0MjktNDYyYy1hNmNhLTk4NmQ3YTE5OWUzYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.ABiQtUvEwk9U0hKtCUmfUmEBa7f6ltnzssjeJ6CQT2WP1Vdlk5LvEp14MjNreu017LjKm29jc0pnDl5WPqscTve7QTjj8hesdPwM5JuJU5BjVCBsgyOuXP8tPKF4IFOejGRp3IDUqPdYcMkjKKY4xFioCzJqp7QOBFldsyfE-gpghzjrwHVLXxGJK8nPrNYcCBeqlPDO2eIWs7LeFWYqxpeYDvvTGlW3YPKAT6-mA2OEIpr0L_Ma_alsXlXkqjdGykQ3SiA5lqlX9L-CvYHvQpzK5QQqAefTin2FU7RVWAmxjg-btdg9KKtEGfXmHZt1WhU5mNHUNQlOg1OQr15JKQ
###

GET http://localhost:8081/admin/realms/demo_shop/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlSFBjTjhrUzQ4aElwbmUxc2JSWnBJblp2dlhrRGFfSHFPdnBxMWVnOGRrIn0.eyJleHAiOjE3Mjc5NDYwMDUsImlhdCI6MTcyNzk0NTk0NSwianRpIjoiOTJhNjQ1NWEtMjEzYS00ZTc0LTk1MzItYjQxMzlmYjUwNDI2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiIwM2U1ZDhiOS0zOTZmLTQ4MzgtOGMwMS1iMWQ0Nzc1M2Y3MWQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzZXNzaW9uX3N0YXRlIjoiYThkY2FiOWEtZWIyNC00MTc5LTk2OWYtZDVjOGM4NGNmZjBkIiwiYWNyIjoiMSIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6ImE4ZGNhYjlhLWViMjQtNDE3OS05NjlmLWQ1YzhjODRjZmYwZCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.AvtpR-hsyv5DS23_t9aNV3MouRIUNUGZnHLJJpLljw-55F6vnbVlMWyCzcuD2_JNCWAb3GMSpuIgdbbJDNAnXQux7mrzb9pZPf1ySdLR4OHnaBkpYFKGC69deJ3SvPy5K5AsIBo9RYcFg_H2vcgUjQT4DDhhfB_iWS9IdkmPkdTCKfsACWQACJxqS6euOwl1Diwgzd96SHbooZoVu_CAJMOnViPD60wOElzGl9-wAHtWT4NahcUGsmrmqdzVXUNA0quOvpatQa76PYe834-oSqn4fI9XxFLrWup5H43ZantpeRtGQcOqnU5ZVR28u7lmFKgnZm4QnoICoElkerDbxg
###
