### GET user
GET http://localhost:3000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0MGViN2I0ZC0wYzgyLTRkNjctYmQxMS1lMjQ0NGZhZWM5NGYifQ.eyJleHAiOjE3MzA3ODgwNjEsImlhdCI6MTczMDc4NjI2MSwianRpIjoiMDQzYjRmYjEtNDBlOS00NDEyLWI5MzEtYjJmYWE2YmE1YTYxIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL3JlYWxtcy9kZW1vX3Nob3AiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvcmVhbG1zL2RlbW9fc2hvcCIsInN1YiI6IjdlOTQzNDFlLTNlNWYtNDc4OS1hMTUwLTQxYzczMWU5MTNhZSIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJkZW1vX3Nob3BfdWkiLCJzZXNzaW9uX3N0YXRlIjoiZTg5MzNhMWEtYWE3MS00MmE5LTliNTYtZjI5ZGI5ZDdiNDY2Iiwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiZTg5MzNhMWEtYWE3MS00MmE5LTliNTYtZjI5ZGI5ZDdiNDY2In0.xaCRMrx8n6-VRWKlSEcoGVqLAPrx0Ay66kDCZko51Nw
