name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  actions: write

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CW_DEPLOY_BOT_ID }}
          private-key: ${{ secrets.CW_DEPLOY_BOT_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/amd64 \
          --build-arg SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" \
          --build-arg SENTRY_ORG="${SENTRY_ORG}" \
          --build-arg SENTRY_DEMO_SHOP_API_PROJECT="${SENTRY_DEMO_SHOP_API_PROJECT}" \
          -f apps/backend/Dockerfile \
          -t demo-shop-api:latest .

      - name: Save docker image to file
        run: docker save demo-shop-api:latest | tee demo-shop-api.tar > /dev/null

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: demo-shop-api.tar
          retention-days: 1

      - name: Cleanup
        if: always()
        run: docker rmi demo-shop-api:latest || true

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CW_DEPLOY_BOT_ID }}
          private-key: ${{ secrets.CW_DEPLOY_BOT_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Build Docker
        run: |
          docker build \
          --platform linux/amd64 \
          --build-arg KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} \
          --build-arg KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} \
          --build-arg KEYCLOAK_CLIENT_UI=${{ secrets.KEYCLOAK_CLIENT_UI }} \
          --build-arg SENTRY_DEMO_SHOP_UI_DSN=${{ secrets.SENTRY_DEMO_SHOP_UI_DSN }} \
          --build-arg SENTRY_TRUSTED_DOMAIN=${{ secrets.SENTRY_TRUSTED_DOMAIN }} \
            -f apps/frontend/Dockerfile \
          -t demo-shop-frontend:latest .

      - name: Save docker image to file
        run: docker save demo-shop-frontend:latest | tee demo-shop-frontend.tar > /dev/null

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: demo-shop-frontend.tar
          retention-days: 1

      - name: Cleanup
        if: always()
        run: docker rmi demo-shop-frontend:latest || true
