name: CI

on:
  push:
    branches:
      - main
      - update-github-workflows
  pull_request:
    branches:
      - main
permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --ignore-scripts

      - run: npx prisma generate

      - name: lint
        run: npx nx run-many -t lint

      - name: test
        run: npx nx run-many -t test --codeCoverage

      - name: build
        run: npx nx run-many -t build
