name: Deploy Terraform Runner

on:
  workflow_dispatch: # Manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .ops/terraform/environments/prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH Keys and Certs
        run: |
          echo "${{ secrets.KEYCLOAK_SSH_PRIVATE_KEY }}" > keycloak_ssh_private_key
          echo "${{ secrets.KEYCLOAK_SSH_PUBLIC_KEY }}" > keycloak_ssh_public_key
          echo "${{ secrets.KEYCLOAK_SERVER_CERT }}" > keycloak_server_cert.pem
          echo "${{ secrets_keycloak_server_key }}" > keycloak_server_key.pem
          chmod 600 keycloak_ssh_private_key keycloak_ssh_public_key *.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_allowed_cidr: ${{ secrets.ALLOWED_CIDR }}
          TF_VAR_keycloak_ssh_public_key_path: './keycloak_ssh_public_key'
          TF_VAR_keycloak_ssh_private_key_path: './keycloak_ssh_private_key'
          TF_VAR_keycloak_server_cert_path: './keycloak_server_cert.pem'
          TF_VAR_keycloak_server_key_path: './keycloak_server_key.pem'
        run: |
          terraform init
          terraform fmt -check
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
