name: pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --ignore-scripts

      - run: npx prisma generate

      - uses: nrwl/nx-set-shas@e2e6dc8bce4b0387a05eb687735c39c41580b792

      - name: lint
        run: npx nx affected -t lint --configuration=ci --base=origin/main

      - name: test
        run: npx nx affected -t test --configuration=ci --codeCoverage --base=origin/main

      - name: build
        run: npx nx affected -t build --base=origin/main

      #      - name: e2e
      #        run: npx nx affected --parallel 1 -t e2e --base=origin/main
