name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Run tests
      - run: npx nx affected -t lint test build --configuration=ci --codeCoverage
      - run: npx nx affected --parallel 1 -t e2e-ci

      # Run quality gate
      - name: sonarcloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
