name: Version

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Dry run'
        default: false

jobs:
  version:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CW_DEPLOY_BOT_ID }}
          private-key: ${{ secrets.CW_DEPLOY_BOT_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configure Git
        run: |
          git config --global user.name 'CW Deploy Bot'
          git config --global user.email 'noreply@github.com'

      - name: Create new version
        if: ${{ !inputs.dry_run }}
        run: |
          touch CHANGELOG.md
          npx standard-version --infile CHANGELOG.md --commit-all
          git push --follow-tags origin main

      - name: Dry run
        if: ${{ inputs.dry_run }}
        run: npx standard-version --dry-run
