name: Version

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Dry run'
        default: false
  push:
    branches:
      - main

jobs:
  version:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new version
        if: ${{ !inputs.dry_run }}
        run: |
          git checkout -b version-update
          touch CHANGELOG.md
          npx standard-version --infile CHANGELOG.md --commit-all

      - name: Create Pull Request
        if: ${{ !inputs.dry_run }}
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          branch: version-update
          title: 'chore: version update'
          body: 'Automated version update'
          commit-message: 'chore: version update'
          delete-branch: true

      - name: Dry run
        if: ${{ inputs.dry_run }}
        run: npx standard-version --dry-run
