name: Version
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Dry run'
        default: false

jobs:
  version:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VERSION_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new version
        if: ${{ !inputs.dry_run }}
        run: |
          touch CHANGELOG.md
          npx standard-version --infile CHANGELOG.md --commit-all
          git push --follow-tags origin main

      - name: Dry run
        if: ${{ inputs.dry_run }}
        run: npx standard-version --dry-run
